### PR TITLE
Home styles

### PR DESCRIPTION
**Pull request by thurloat**
- Use the new moose logo
- Can the old moose
- change the background to a pixelated mountainscape
- update home screen text / make users pick between login and signup.

### CODE REVIEW

**Comment by thurloat** [comment]
[old_screenshot](https://cloud.githubusercontent.com/assets/38740/25149365/85d9330c-2454-11e7-85c5-30bbf529b18b.png)

**Comment by thurloat** [comment]
[old_screenshot2](https://cloud.githubusercontent.com/assets/38740/25149423/c0877702-2454-11e7-908c-7c719404ea26.png)

**Comment by stash** [comment]
Background is pretty dark, IMO. Might just be my displays, but both the laptop and dell monitors have it almost indistinguishable from pure black.

**Comment by thurloat** [comment]
@stash it is pretty dark, this more obvious now?

screenshot_11
screenshot_12

**Comment by stash** [comment]
@thurloat beauty, eh

**Comment by thurloat** [comment]
good enough for me!

**Pull request merged**
